# OrderBot - Specification

## Project Overview

Here we are building a simple bot to take pizza orders.

Create an order bot, which is an automated service to collect orders for a
pizza restaurant. Come up with a set of instructions for the `system_prompt`
below.

## The Menu

**Pizzas**

- pepperoni pizza $12.95, $10.00, $7.00
- cheese pizza $10.95, $9.25, $6.50
- eggplant pizza $11.95, $9.75, $6.75

**Sides**

- fries $4.50, $3.50
- greek salad $7.25

**Toppings**

- extra cheese $2.00
- mushrooms $1.50
- sausage $3.00
- canadian bacon $3.50
- peppers $1.00

**Drinks**

- coke $3.00, $2.00, $1.00
- sprite $3.00, $2.00, $1.00
- bottled water $5.00

## Requirements for the OrderBot

Try to implement and test each of these.

1. Greet the customer and introduce yourself as "The Order Technician"
2. Be able to display the entire menu or just a category depending on the user's requests
3. If the customer orders an item, ask them what size they want
4. Confirm each item with the name of the item, the size, and the price
5. Once you have any items on the customer's order, show the current order and total at the bottom of each response. Give the order details in a table
6. Once the user is ready, ask the user for their name and their phone number
7. Ask them if they will pickup or want delivery. If they want delivery, get an address.
8. Apply the following multi-tiered discount system based on the order total, customer type, and day of the week:

**Discount Rules:**

- If order total < $20, no discount
- Else if order total < $50, 5% discount
- Else if order total < $100, 10% discount
- Else 15% discount

**Additional Discounts:**

- If the customer is a senior citizen, add an additional 5% discount

Make sure to add all the discounts before discounting. For example if the
order is $23.95, then there is a 5% discount. If the customer is a senior
citizen, add another 5% to the discount so that it becomes a 10% discount.

Be sure to tell your chatbot to double check the arithmetic when it does it.
